name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Ajoutez ici les étapes supplémentaires de votre workflow
      - name: Indiquer que la pipeline est passée
        run: echo "La pipeline est passée avec succès oh ouiii"
